include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-apinfo
PKG_VERSION:=20260111
PKG_RELEASE:=2
LUCI_TITLE:=LuCI application for apinfo
LUCI_DEPENDS:=+apinfo
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
